### ISSUE TITLE
書き方

### ISSUE THREAD

**Issue by C0A21145** [MinamiSawamura/ProjExD#2]
https://github.com/MinamiSawamura/ProjExD/blob/068d0f79c2660576f00c56168b54ecd93c33047e/ex01/alphabet.py#L17

事前に配列に入る文字数が分かっているから、appendではなくて同じ長さの配列を作っておいた方が処理が速くなると思います

**Comment by MinamiSawamura** [comment]
修正しました！！

**Comment by MinamiSawamura** [comment]
修正完了しました
