### ISSUE TITLE
デバッグ用

### ISSUE THREAD

**Issue by c0a2113791** [MinamiSawamura/ProjExD#3]
https://github.com/MinamiSawamura/ProjExD/blob/068d0f79c2660576f00c56168b54ecd93c33047e/ex01/alphabet.py#L24
次回動かすときに表示されないためにコメントアウト等の対処をしといたほうがいいと思います。

**Comment by MinamiSawamura** [comment]
修正しました！！

**Comment by MinamiSawamura** [comment]
修正完了しました
